import { Router, type IRouter } from "express";
import healthRouter from "./health";
import projectsRouter from "./projects";
import filesRouter from "./files";
import aiRouter from "./ai";
import executeRouter from "./execute";
import downloadRouter from "./download";
import adminRouter from "./admin";
import scriptsRouter from "./scripts";
import guiRouter from "./gui";
import previewRouter from "./previews";
import apkRouter from "./apk";
const router: IRouter = Router();
router.use(healthRouter);
router.use(projectsRouter);
router.use(filesRouter);
router.use(aiRouter);
router.use(executeRouter);
router.use(downloadRouter);
router.use(guiRouter);
router.use(previewRouter);
router.use(apkRouter);
router.use(adminRouter);
router.use(scriptsRouter);
export default router;
